[target.'cfg(target_arch="x86_64")']
rustflags = ["-C", "target_cpu=x86-64-v3", "-C", "target-feature=+aes"]

[target.'cfg(target_arch="aarch64")']
rustflags = ["-C", "target-feature=+aes"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.aarch64-apple-darwin]
linker = "rust-lld"
