[package]
name = "korangar"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
bytemuck = { version = "1.9", features = ["derive", "extern_crate_std", "min_const_generics"] }
cgmath = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
collision = { git = "https://github.com/rustgd/collision-rs.git" }
derive-new = { workspace = true }
image = "0.24.2"
korangar_interface = { workspace = true, features = ["serde", "cgmath"] }
lunify = "1.1.0"
mlua = { version = "0.8", features = ["lua51", "vendored"] }
num = { workspace = true }
# TODO: Remove or move to workspace
option-ext = "0.2.0"
pathfinding = "2.2.2"
korangar_debug = { workspace = true, optional = true }
korangar_procedural = { workspace = true }
ragnarok_bytes = { workspace = true, features = ["derive", "cgmath"] }
ragnarok_networking = { workspace = true, features = ["derive", "interface"] }
rand = "0.8.5"
random_color = { version = "0.6.1", optional = true }
rayon = "1.5.3"
ron = "0.8.0"
rusttype = { version = "0.9.2", features = ["gpu_cache"] }
serde = { workspace = true }
serde-xml-rs = "0.6.0"
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "db3df4e55f80c137ea6187250957eb92c2291627" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "db3df4e55f80c137ea6187250957eb92c2291627" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "db3df4e55f80c137ea6187250957eb92c2291627" }
walkdir = "2"
winit = "0.28.7"
xml-rs = "0.8.0"
yazi = "0.1.4"

[features]
patched_as_folder = []
debug = ["korangar_debug", "ragnarok_networking/debug", "random_color"]
unicode = ["debug"]
plain = ["debug"]
